version: '3.8'

services:
  eboxtenders-prod-app:
    container_name: eboxtenders-prod-app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    ports:
      - "${HOST_PORT}:${PORT}"  # host:container port mapping
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3002}
    restart: unless-stopped
